name: Build and test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install deps (MacOS)
        run: brew install git-annex
        if: matrix.os == 'macos-latest'

      - run: pip install cram

      - run: ls /usr/local/bin

      - run: which git-annex
